force-app/main/default/objects/TestData__c/TestData__c.object-meta.xml
<CustomObject>
    <description>CCA HW11, Custom sObj for testing (Leads only in this HW).  Used in</description>
    <label>TestData</label>
    <nameField>
        <displayFormat>TD-{00000}</displayFormat>
        <label>TestData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TestData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestData__c/fields/AssertedOutcome__c.field-meta.xml
<CustomField>
    <fullName>AssertedOutcome__c</fullName>
    <label>AssertedOutcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TestData__c/fields/AssertedValue__c.field-meta.xml
<CustomField>
    <fullName>AssertedValue__c</fullName>
    <label>AssertedValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestData__c/fields/FieldValue__c.field-meta.xml
<CustomField>
    <fullName>FieldValue__c</fullName>
    <label>FieldValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestData__c/fields/sObjectName__c.field-meta.xml
<CustomField>
    <fullName>sObjectName__c</fullName>
    <label>sObjectName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandlerTest.cls
@IsTest
public with sharing class LeadTriggerHandlerTest {
    
    @IsTest
    public static void testLeadTitleNormalization() {
        
        List<Lead> testLeads = new List<Lead>();
        
        List<TestData__c> testData = [
            SELECT 
                Id, 
                sObjectName__c, 
                FieldName__c, 
                FieldValue__c, 
                AssertedValue__c, 
                AssertedOutcome__c 
            FROM TestData__c
            WHERE
                SObjectName__c = 'Lead' AND
                FieldName__c = 'Title'
            ];

        for (TestData__c tf : testData) {
            Lead newTestLead = new Lead();
            Integer newLeadNum = 0;
            if (tf.sObjectName__c == 'Lead') {
                newTestLead.FirstName = 'test';
                newTestLead.LastName = 'lead' + String.valueOf(newLeadNum);
                newTestLead.title = tf.FieldValue__c;
                newTestLead.LeadSource = 'Web';
                newTestLead.Email = 'test@test.com';
                testLeads.add(newTestLead);
            }
        }

        test.startTest();
        insert testLeads;
        test.stopTest();

        System.assert(testLeads.size() > 0);
    
    }  
    
}